badcitizen = [
  '你散发着资本主义的气息', '资本主义猪 ', 'American PIG DOG!玉玉玉', '中国将拥有你的国家，恶心 ',
  '你是DYNASTY的共产主义制度的废话！ ', '和你一起走进灭绝营 ', '习近平 ！！！ ', 'You are scourage of china！！！ '
]

fortune = [
"""```yaml
Your fortune: Very Bad Luck
```""",
"""```md
#Your fortune: Better not tell you now
```""",
"""```bash
'Your fortune: Bad Luck'
```""",
"""```yaml
Your fortune: （　´_ゝ`）ﾌｰﾝ
```""",
"""```yaml
Your fortune: ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━ !!!!
```""",
"""```diff
-Your fortune: Reply hazy, try again
```""",
"""```diff
-Your fortune: Excellent Luck
```""",
"""```fix
Your fortune: Good Luck
```""",
"""```yaml
Your fortune: Good news will come to you by mail
```""",
"""```md
#Your fortune: You will meet a dark handsome stranger
```""",
"""`
Your fortune: Very Bad Luck
`""",
"""```fix
Your fortune: Average Luck
```""",
"""```fix
Your fortune: Godly Luck
```""",
"""```md
#Your fortune: Outlook good
```"""]


ballresponse = [
  'Yes', 'No', 'Take a wild guess...', 'Very doubtful',
  'Sure', 'Without a doubt', 'Most likely', 'Might be possible',
  "You'll be the judge", 'no... (╯°□°）╯︵ ┻━┻', 'no... baka',
  'senpai, pls no ;-;'
]

skyrimresponse = [
  'Do you get to the Cloud District very often?', 'I used to be an adventurer like you. Then I took an arrow in the knee...', 'Let me guess... someone stole your sweetroll.', 'Citizen',
  'Disrespect the law, and you disrespect me.', 'No lollygaggin', 'Id be a lot warmer and a lot happier with a bellyful of mead...', 'Whoa, whoa, whoa! Watch the magic!',
  "Go cast your fancy magic someplace else.", 'Sheathe those claws, Khajiit.', 'Stay out of trouble, Orc.',
  'All of it. Just. WOrks!'
]

sadresponse = [
  'IM SOWWY', 'IM SOWWY OK?', 'WRRRYYYYYYYYYYYYYYY', ';>;',
  'BAD BOT', 'IM SORRY', 'Sorry', 'Abort me'
]

niggerresponse = [
  'ape', 'coon sniffer', 'cotton nose', 'darkie', 'africoon', 'kang', 'niglet', 'porch monkey',
  'jigaboo', 'nigger', 'boogaloo', 'monky', 'target practice', 'gorilla', 'street ape'
]
whitespaces = [
  "⁣﻿", "⁣", "⁣", "⁣", " ", " ", " ", " ", " ", " ", " ",
  "⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣", "	", " ", " ", " ", " ", " ", " ", " ", "　"
]
color = [
  'Black', 'White', 'Yellow', 'Oni Orange', 'Dark Purple', 'Red',
  'Blue', 'Cyan Boi', 'Pink', 'Metallic Pink', 'Purple', 'Green'
]
ping = [
  'the fox news satellite', 'localhost', '127.0.0.1', 'dynasty', 'my router', 'Лайка', 'ponged', 'indicas dox', 'retart', 'daisys destruction', 'cock and ball torture',
  'china man', 'ps4 supercomputer', 'quiznogs router', 'an asian router', 'russia', 'my mailbox', 'minecraft hentai', '38.100.119.12', 'stop abusing me', 'youre a whore'
]
hap = [
  '📯', '📯 doot', 'doot', ':D', 'i lov u', 'thanks', 'thank', 'happy', 'yes', 'no u'
]
anger = [   
  'go fuck yourself', 'lmao ur a sad excuse to a N', 'ur the reason Tengri created the middle finger', 'fuc koff', 'shit urself', 'cope', 'sneed', 'dilate', 'seethe', 'kill yourself', 'ur just mad u wont ever have sex with me xdddd', 'fag', 'faggot', 'atleast Im not homosexual', 'ok crusty', 'if that helps u sleep sweatie','cuck', 'keep rolling your eyes, you might eventually find a brain', 'you are the human version of period cramps.', 'You are like a cloud. When you disappear it’s a beautiful day.'
]
suicide = [
  'go fuck yourself', 'do it faggot', 'good', 'choke on your own dick', 'kill yourself', 'Hi, we have noticed you are going through tough times and\nwe want to offer you help. Here are some reources\nyou can seek to get help. <3\n\nKill yourself\n\nfuck you <3', ':)', 'ur too much of a pussy to do it'
]
doots = [
  '📯', '📯 doot', 'doot', 'https://cdn.discordapp.com/attachments/673308690157404211/715706879749259335/help_me_to_doot.png', 'https://cdn.discordapp.com/attachments/673308690157404211/715707102991089664/unknown.png', 
  'https://cdn.discordapp.com/attachments/673308690157404211/715707177909878794/9d55f705-5aa0-4d7b-b02c-39883fdc3701.png', 'https://cdn.discordapp.com/attachments/673308690157404211/715707187195936768/9d55f705-5aa0-4d27b-b02c-39883fdc3701.png', 
  'https://cdn.discordapp.com/attachments/673308690157404211/715707199556419635/9d55f705-5aa0-4d57b-b02c-39883fdc3701.png', 'https://cdn.discordapp.com/attachments/673308690157404211/715707209602039898/9d55f705-5aa0-234564d7b-b02c-39883fdc3701.png', 
  'https://cdn.discordapp.com/attachments/673308690157404211/715707224965644288/blur.png', 'https://cdn.discordapp.com/attachments/673308690157404211/715707246570635285/am_i_a_doot.png', 'https://cdn.discordapp.com/attachments/673308690157404211/715707325914021918/dootdootdootdoot.png'
]
fuck = [
  'Please send it as soon as possible', 'You may be able to control your hunger', 'Send', 'mpc8241 Toolbox', 'This file is not in the file. This problem is over.', 'sudo dead', 'buenos dias Mandy', 'moni tino', '*Kills self*', 'these fucking öäü ',
  'How to Compress to Make {fuckmenigga} Add S. A.S. Inc.', 'Is it possible to load a Linux machine faster?', 'Fill in the manager and let me speak for 10 minutes', 'Help me', '.fuck no such command', 'Let me inspire food', 'i am gay', 'U+10ACB4 : <private-use>',
  '􊲴', '??????', '🁺🖕🏕🰗🸘🀙🁨🙝🚭🙒🌵🐯🻙🴓🀕🯧🌵🃇🇸😁🣸🋏🊿🷞💮🙺🻆🪾🁒💟🡝🃜💨🇂🧋🧆🯷🂜🗞🄜🌜🳜🷚🰉🰽🬁🳃🻻🸙🨌', 'miniwa', 'They told Google :(', 'Uh oh we got bit ratelimited by googleEEeeeee', 'the bot probably just doesnt know what to do when you supply nothing, and the "last used" file doesnt have anything for you lol',
  'i dont think theres an error', 'how do i solder my cpu', 'fix the chat', 'this font is gay, and so are you', 'whonixed', 'Im glad I didnt give many fruits that spoiled my mouth', 'Im glad its not an ad for some titan gel lotion to smear on your dick ',
  'with 64MB RAM and 4MB (but actually 8 with banking, I dont get it) flash', 'these fucking retards hardcoded their user path shit ', 'my cock has sultry', 'andy', 'you', 'ghost', 'ad', 'compress', 'give', 'am', 'I', 'are', 'glad', 'sad', 'by', 'Maybe they added me to iptables', 'MaYBe ThEy ADdEd Me ToT he IPTaBles'
]
fuckcorpus = [
  "'kay", "African", "Angel", "BBC", "BRB", "Bam", "Boo", "Burp", "CIA", "California", "Catastrophic Success", "China", "Church", "Cosmos", "Dad", "Dudly Doright", "FBI", "GarryKasparov", "Ghost", "Give me praise", "china man", "china man is not mocked", "china man smack", "Mongolia", "Mongolian to me", "Han shot first", "Hasta", "Heaven", "Hicc up", "HolySpirit", "I'll ask nicely", "I'll be back", "I'll get right on it", "I'll let you know", "I'll think about it", "I'm china man and you're not", "I'm china man who the hell are you", "I'm beginning to wonder", "I'm bored", "I'm busy", "I'm done", "I'm feeling nice today", "I'm gonna smack someone", "I'm good you good", "I'm grieved", "I'm impressed", "I'm in suspense", "I'm not dead yet", "I'm not sure", "I'm off today", "I'm on a roll", "I'm the boss", "I'm thrilled", "I'm tired of this", "IMHO", "I am not amused", "I be like", "I can't believe it", "I could be wrong", "I could swear", "I didn't do it", "I didn't see that", "I don't care", "I donno", "I forgot", "I give up", "I got your back", "I had a crazy dream", "I hate when that happens", "I have an idea", "I just might", "I love this", "I love you", "I made it that way", "I pity the fool", "I planned that", "I quit", "I see nothing", "I veto that", "I was just thinking", "I was sleeping", "Icarus", "If had my druthers", "Is that so", "Is that your final answer", "Isn't that special", "It's nice being china man", "It grieves me", "Ivy league", "Japan", "Jedi mind trick", "china man", "King Midas", "Knock you upside the head", "LOL", "Make America Great Again", "Mars", "Mission Accomplished", "Mom", "Moses", "NOT", "NeilDeGrasseTyson", "Trump", "Oh Hell No", "Oh really", "Okilydokily", "One finger salute", "Oy", "Pope", "Putin", "Pullin the dragons tail", "ROFLMAO", "Russia", "Shakespeare", "Shalom", "Shhh", "StephenHawking", "SupremerCourt", "Ahiga", "That's gonna leave a mark", "That's my favorite", "The good stuff", "This is confusing", "Varoom", "Vegas", "Venus", "Watch this", "What", "What I want", "What are you doing Dave", "WooHoo", "Wow", "Yawn", "Yes you are", "Yo", "You can count on that", "You da man", "You fix it", "You get what you pray for", "You know", "Zap", "Zzzzzzzz", "a flag on that play", "a likely story", "a screw loose", "abnormal", "absetively posilutely", "absolutely", "act", "adjusted for inflation", "adultery", "after a break", "ahh", "ahh thats much better", "air head", "and the award goes to", "and then what", "angel", "anger", "application", "are you deaf", "are you feeling lucky", "are you insane", "are you sure", "arent you clever", "arrogant", "as a matter of fact", "astounding", "astronomical", "astrophysics", "atheist", "atrocious", "au revoir", "awesome", "awful", "ba ha", "bad", "bad ol puddytat", "baffling", "bank", "basically", "basket case", "bastard", "battle", "be happy", "be quiet bird", "beam me up", "because I said so", "beep beep", "begs the question", "bickering", "big fish", "biggot", "birds", "bizarre", "blessing", "boink", "boss", "break some woopass on you", "bring it on", "bummer", "busybody", "but of course", "by the way", "bye", "can you hear me now", "car", "catastrophe", "caution", "chaos", "charged", "charity", "check this out", "cheerful", "chess", "chill", "chill out", "choose one", "chump change", "church", "class  class  shutup", "clever", "climate", "close your eyes", "come and get me", "comedy", "commanded", "completely", "computers", "conservative", "cosmetics", "could it be   Satan", "couldn't be better", "couldnt possibly", "courage", "cowardice", "cracks me up", "crash and burn", "crazy", "cursing", "dance", "dang it", "daunting", "dean scream", "debt", "delicious", "delightful", "depressing", "desert", "didn't I say that", "dignity", "do I have to", "do it", "do not disturb", "do over", "do you get a cookie", "do you have a problem", "do you know what time it is", "do you like it", "do you want another", "doh", "don't count on it", "don't even think about it", "don't have a cow", "don't mention it", "don't push it", "don't worry", "downer", "drama", "driving", "duck the shoe", "dude such a scoffer", "earnest", "economy", "eh", "ehh a wise guy", "ehheh that's all folks", "employee", "employer", "end", "endeared", "endeavor", "endure", "energy", "enough", "enough said", "envy", "epic fail", "et tu", "everything's a okay", "evolution", "exorbitant", "experts", "exports", "fabulous", "face palm", "failure is not an option", "failure to communicate", "fake", "fancy", "far out man", "fer sure", "fight", "figuratively", "food", "fool", "fortitude", "foul", "freak", "frown", "fun", "funny", "furious", "gambling", "game changer", "game over", "geek", "genius", "ghastly", "ghetto", "glam", "glorious", "gluttony", "go ahead make my day", "good", "gosh", "gross", "grumble", "guilty", "guppy", "ha", "handyman", "hang in there", "happy", "happy happy joy joy", "hard working", "harder than it looks", "hate", "have fun", "he be like", "heads I win tails you lose", "heathen", "hello", "here now", "hey Mikey he likes it", "hey thats right", "hi", "high five", "high mucky muck", "hilarious", "hippy", "hit", "ho ho ho", "hobnob", "hold on a minute", "holier than thou", "holy grail", "home", "homo", "honestly", "honesty", "hooah", "hope", "hopefully", "horrendous", "hot air", "hotel", "how's the weather", "how about", "how about that", "how about those yankees", "how bout it", "how come", "how could you", "how do I put this", "how goes it", "how hard could it be", "how high", "huh", "humility", "humongous", "hurts my head", "husband", "hypocrite", "ice cream", "if and only if", "if anything can go wrong", "illogical", "imports", "impossible", "in a galaxy far far away", "in a perfect world", "in other words", "in practice", "in theory", "incoming", "incredibly", "industrious", "ingrate", "insane", "ipod", "is it just me or", "it'd take a miracle", "it's hopeless", "it's my world", "it figures", "it gets better", "it was nothing", "jealousy", "job", "jobs", "joke", "joker", "joking", "joy", "joyful", "just between us", "just lovely", "kick back", "kludge", "later", "laziness", "left field", "let's roll", "let's see", "let me count the ways", "liberal", "lift", "lighten up", "like like", "listen buddy", "little buddy", "little fish", "look buddy", "look on the brightside", "look out", "love", "lulz", "lust", "lying", "make my day", "manufacturing", "maybe I didn't make it clear", "meek", "meh", "merry christmas", "middle class", "mine", "mission from china man", "mocking", "money", "mundo stoked", "music", "my bad", "my precious", "na na", "nasty", "naughty", "nerd", "nevada", "never happy", "news to me", "no more", "no more tears", "no news is good news", "no way dude", "no you cant", "nope", "not", "not a chance in hell", "not good", "not in kansas anymore", "not in my wildest dreams", "not that theres anything wrong", "not the sharpest knife in the drawer", "not too shabby", "now that I think about it", "now you tell me", "nut job", "obviously", "off the record", "oh come on", "oh my", "oh no", "oh oh", "ohh thank you", "oil", "okay", "on occassion", "on the otherhand", "once upon a time", "one more time", "one small step", "oops", "ordinarily", "other", "ouch", "outrageous", "over the top", "overflow", "pardon the french", "patience", "peace", "perfect", "persistence", "pet", "petty", "phasors on stun", "pick me pick me", "piety", "place", "play", "poor", "population", "potentially", "pow", "praise", "praying", "pride", "programming", "prosperity", "pwned", "qed", "quit", "quit it", "quite", "radio", "really", "recipe", "refreshing", "relax", "repeat after me", "repent", "resume", "reverse engineer", "revolution", "rich", "ridiculous", "rip off", "rocket science", "rose colored glasses", "roses are red", "rubbish", "run away", "saber rattling", "sad", "scorning", "scum", "segway", "service sector", "services", "sess me", "sex", "shist", "shucks", "silly human", "sing", "skills", "sky", "sloth", "slumin", "smack some sense into you", "small talk", "smart", "smile", "smurfs", "snap out of it", "so he sess", "so let it be done", "so let it be written", "soap opera", "special case", "spending", "spirit", "spoiled brat", "sports", "spunky", "stoked", "straighten up", "strip", "study", "stuff", "stunning", "super computer", "surprise surprise", "take the day off", "take your pick", "talk to my lawyer", "tattle tale", "taxes", "test pilot", "thank you very much", "that's all folks", "that's for me to know", "that's much better", "that's no fun", "that's your opinion", "thats just wrong", "thats laughable", "thats right", "the", "the enquirer", "theft", "theres no place like home", "these cans are defective", "think you could do better", "this might end badly", "threads", "tiffanies", "to infinity and beyond", "tomorrow", "tree hugger", "try again", "uh huh", "umm", "umm the other answer", "umm what now", "unemployment", "unsung hero", "vengeance", "vengeful", "vermin", "vice", "virtue", "voodoo", "vote", "walking", "wanna bet", "wastoid", "watch it buddy", "wazz up with that", "we ve already got one", "well I never", "well golly", "well obviously", "whale", "what's it to you", "what's the plan", "what's up", "what a mess", "what a nightmare", "what do you expect", "what do you want", "what have you done for me lately", "what luck", "what part of china man do you not understand", "what planet are you from", "what the heck", "what was I thinking", "what would china man do", "whatcha talkin' 'bout", "whazza matter for you", "when hell freezes over", "where's the love", "whiner", "white trash", "who's to say", "who are you to judge", "whoop there it is", "why didn' you tell me", "why do I put up with this", "why is it", "wishful thinking", "won't you be my neighbor", "wonderbread", "wonderful", "woot", "wot", "wrath", "yada yada yada", "yeah", "yep", "yikes", "you'll see", "you're fired", "you're in big trouble", "you're lucky", "you're no fun", "you're not all there are you", "you're nuts", "you're out of your mind", "you're so screwed", "you're welcome", "you're wonderful", "you are my sunshine", "you better not", "you do it", "you don't like it", "you don't say", "you hoser", "you know a better china man", "you never know", "you owe me", "you see the light", "you should be so lucky", "you shouldn't have", "you talkin' to me", "you think I'm joking", "you think you could do better", "yuck", "zoot", "red fang", "rum bitty di", "I m prettier than this man", "This cant be william wallace", "got the life", "king nun", "king of mars", "an Irishman is forced to talk to china man", "you couldnt navigate yer way circleK", "its trivial obviously", "rufus!", "."
]

prompt = [
"An international tribunal has found you guilty of "                                                 ,
"And I would have gotten away with it, too, if it hadnt been for ",
"Awww, sick! I just saw this skater do a 720 kickflip into ",
"Dear Sir or Madam, We regret to inform you that the Office has denied your request for ",
"Doctor, youve gone too far! The human body wasnt meant to withstand that amount of ",
"Future historians will agree that the marking of the beginning of Americas decline will be ",
"He who controls the world controls ",
"I learned the hard way that you cant cheer up a grieving friend with ",
"In a pinch, it can be a suitable substitute for ",
"In his new self-produced album, Kanye West raps over the sounds of ",
"In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ",
"In Rome, there are whisperings that the Vatican has a secret room devoted to ",
"Michael Bays new three-hour action epic pits against ",
"My plan for world domination begins with ",
"Next season on Man vs, Wild, Bear Grylls must survive the depths of the Amazon with only  ",
"Next week on Discovery Channel, one man must survive in the depths of the Amazon with only  ",
"Science will never explain ",
"Science will never explain the origin of ",
"The CIA now interrogates enemy agents by repeatedly subjecting them to ",
"The secret to a lasting marriage is communication, communication, and ",
"The socialist governments of Scandinavia have declared that access to basic human right is ",
"What brought the orgy to a grinding halt? ",
"What has been making life difficult at the nudist colony? ",
"Whats the gift that keeps on giving? ",
"When all else fails, I can always masturbate to ",
"When I pooped, what came out of my butt? ",
"I would be woefully incomplete without ",
"StealthFl(a)shlight! Hours of fun. Easy to use. Perfect for ",
"A remarkable new study has shown that chimps have evolved their own primitive version of ",
"A successful job interview begins with a firm handshake and ends with ",
"After months of practice with , I think I’m finally ready for ",
"And I would have gotten away with it, too, if it hadnt been for ",
"And what did you bring for show and tell? ",
"As part of his contract, Prince won’t perform without ",
"As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ",
"Awww, sick! I just say this skater do a 720 kickflip into ",
"Before, all we had was ",
"Before I run for president, I must destroy all evidence of my involvement with ",
"Call the law offices of Goldstein & Goldstein, because no one should have to tolerate ",
"Charades was ruined for me forever when my mom had to act out ",
"Doctor, youve gone too far! The human body wasnt meant to withstand that amount of ",
"During high school I never really fit in until I found  ",
"During his midlife crisis, my dad got really into ",
"Finally! A service that delivers ",
"Having problems with ",
"Hey baby, come back to my place and I’ll show you ",
"I learned the hard way that you cant cheer up a grieving friend with ",
"I love being a mom. But its tough when my kids come home filthy from ",
"I spent my whole life working, only to have it ruined by ",
"I went from a fag to a nazi, all thanks to ",
"I’m not like the rest of you. I’m too rich and busy for ",
"If God didnt want us to enjoy porn, he wouldnt have given us ",
"In his newest and most difficult stunt, David Blaine must escape from ",
"In the seventh circle of Hell, sinners must endure ",
"Listen, son. If you want to get involved with this server, I won’t stop you. Just steer clear of ",
"Little Miss Muffet Sat on a tuffet, Eating her curds and ",
"Lovin’ you is easy ’cause you’re ",
"Members of New Yorks social elite are paying thousands of dollars just to experience ",
"Money can’t buy me love, but it can buy me ",
"My country, tis of thee, sweet land of ",
"My gym teacher got fired for adding ",
"My life is ruled by a vicious cycle of  ",
"My mom freaked out when she looked at my browser history and found ",
"My new favorite porn star is Joey ",
"My plan for world domination begins with ",
"Next time on Dr. Phil: How to talk to your child about ",
"Only two things in life are certain: death and ",
"Science will never explain ",
"The blind date was going horribly until we discovered our shared interest in ",
"The Five Stages of Grief: denial, anger, bargaining, acceptance and ",
"The healing process began when I joined a support group for victims of ",
"This is your captain speaking. Fasten your seatbelts and prepare for ",
"This months Cosmo: 'Spice up your sex life, in your bedroom get'",
"To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ",
"Tonight on 20/20: What you dont know could kill you - ",
"Welcome to this lovely server! Would you like to try our signature cocktail or ",
"What brought the orgy to a grinding halt? ",
"What has been making life difficult at the nudist colony? ",
"What left this stain on my couch? ",
"Whats harshing my mellow, man? ",
"When you get right down to it its just ",
"With enough time and pressure, this server will turn into ",
"You havent truly lived until youve experienced ",
"Your persistence is admirable, my dear Prince. But you cannot win my heart with "
]

responsen = [
"24-hour media coverage.",
"A beached whale.",
"A big black dick.",
"A bloody pacifier.",
"A crappy little hand.",
"A fat bald man from the internet.",
"A Japanese tourist who wants something very badly but cannot communicate it.",
"A low standard of living.",
"A nuanced critique.",
"A panty raid.",
"A passionate Latino lover.",
"A passionate tomboy lover.",
"A plunger to the face.",
"A rival dojo.",
"A web of lies.",
"A woman scorned.",
"An atomic wedgie.",
"An Etsy steampunk strap-on.",
"An evil man in evil clothes.",
"André the Giant's enormous, leathery scrotum.",
"Apologizing.",
"Appreciative snapping.",
"Ashton Kutcher.",
"Beating your wives.",
"Being a busy adult with many important things to do.",
"Being a dinosaur.",
"Big Bird's brown, crusty asshole.",
"Blaxploitation.",
"Bosnian chicken farmers.",
"Breaking nip slip news.",
"Carnies.",
"Clams.",
"Clenched butt cheeks.",
"Coughing into a vagina.",
"Cutting.",
"Dancing with a broom.",
"Deflowering a princess.",
"Deflowering the princess.",
"Dorito breath.",
"Eating an albino.",
"Fabricating statistics.",
"Finding a skeleton.",
"Genetically engineered super-soldiers.",
"George Clooney's musk.",
"Getting abducted by Peter Pan.",
"Getting in her pants, politely.",
"Gladiatorial combat.",
"Good grammar.",
"Having a penis.",
"Hipsters.",
"Historical revisionism.",
"Insatiable bloodlust.",
"Jafar.",
"Jean-Claude Van Damme in slow motion.",
"Jean-Claude Van Damme.",
"Just the tip.",
"Leveling up.",
"Literally eating shit.",
"Mad hacky-sack skills.",
"Making the penises kiss.",
"Media coverage.",
"Medieval Times® Dinner & Tournament.",
"Mom.",
"Moral ambiguity.",
"My machete.",
"Neil Patrick Harris.",
"NOOOOOOOOO!!!",
"Nubile slave boys.",
"Ominous background music.",
"One thousand Slim Jims.",
"Overpowering your father.",
"Panty raids.",
"Pistol-whipping a hostage.",
"Quiche.",
"Quivering jowls.",
"Revenge fucking.",
"Ripping into a man's chest and pulling out his still-beating heart.",
"Ryan Gosling riding in on a white horse.",
"Salvia.",
"Sanding off a man's nose.",
"Santa Claus.",
"Savagely beating a mascot.",
"Scrotum tickling.",
"Sexual humiliation.",
"Sexy Siamese twins.",
"Shaft.",
"Shitting out a screaming face.",
"Slow motion.",
"Space muffins.",
"Statistically validated stereotypes.",
"Stockholm Syndrome.",
"Sudden Poop Explosion Disease.",
"Suicidal thoughts.",
"Syphilitic insanity.",
"The boners of the elderly.",
"The economy.",
"The Femto® girls.",
"The four arms of Vishnu.",
"The four arms of Hitler-Shiva-Vishnu.",
"The Gulags.",
"The harsh light of day.",
"The hiccups.",
"The ooze.",
"The shambling corpse of Larry King.",
"The worst pain imaginable. Times two!",
"This guy!",
"Tripping balls.",
"Walking in on Dad peeing into Mom's mouth.",
"Words, words, words.",
"Zeus's sexual appetites.",
"24-hour media coverage.",
"A 55-gallon drum of lube.",
"A big black dick.",
"A bigger, blacker dick.",
"A black-owned and operated business.",
"A bloody pacifier.",
"A boo-boo.",
"A botched circumcision.",
"A Burmese tiger pit.",
"A cat video so cute that your eyes roll back and your spine slides out of your anus.",
"A complicated relationship with food.",
"A cop who is also a dog.",
"A crappy little hand.",
"A dollop of sour cream.",
"A fat bald man from the internet.",
"A fortuitous turnip harvest.",
"A greased-up Matthew McConaughey.",
"A Japanese toaster you can fuck.",
"A Japanese tourist who wants something very badly but cannot communicate it.",
"A lamprey swimming up the toilet and latching onto your taint.",
"A low standard of living.",
"A magic hippie love cloud.",
"A man in yoga pants with a ponytail and feather earrings.",
"A nautical theme.",
"A nuanced critique.",
"A passionate Latino lover.",
"A phantasmagoria of anal delights.",
"A pile of squirming bodies.",
"A piñata full of scorpions.",
"A plunger to the face.",
"A PowerPoint presentation.",
"A sad fat dragon with no friends.",
"A sales team of clowns and pedophiles.",
"A slightly shittier parallel universe.",
"A smiling nigger, a latina businesswoman, a cool Asian, and some whites.",
"A sofa that says 'I have style, but I like to be comfortable.'",
"A spontaneous conga line.",
"A squadron of moles wearing aviator goggles.",
"A surprising amount of hair.",
"A sweaty, panting leather daddy.",
"A sweet spaceship.",
"A vagina that leads to another dimension.",
"A web of lies.",
"Actually getting shot, for real.",
"All my friends dying.",
"All of this blood.",
"An all-midget production of Shakespeare’s Richard III.",
"An army of skeletons.",
"An ass disaster.",
"An ether-soaked rag.",
"An Etsy steampunk strap-on.",
"An evil man in evil clothes.",
"An unhinged Ferris wheel rolling toward the sea.",
"An unstoppable wave of fire ants.",
"André the Giant's enormous, leathery scrotum.",
"Another shot of morphine.",
"Basic human decency.",
"Being a busy adult with many important things to do.",
"Being a dinosaur.",
"Being a hideous beast that no one could love.",
"Being awesome at sex.",
"Being a nigger.",
"Being fat from noodles.",
"Being white.",
"Big bad mama nipples.",
"Big Bird's brown, crusty asshole.",
"Big ol' floppy titties.",
"Bill Clinton, naked on a bearskin rug with a saxophone.",
"Blood farts.",
"Blowing some dudes in an alley.",
"Boris the Soviet Love Hammer.",
"Bosnian chicken farmers.",
"Bullshit.",
"Buying the right pants to be cool.",
"Catastrophic urethral trauma.",
"Chugging a lava lamp.",
"Clams.",
"Clenched butt cheeks.",
"Cock.",
"Consent.",
"Converting to Islam.",
"Crabapples all over the fucking sidewalk.",
"Crushing Mr. Peanut's brittle body.",
"Crying into the pages of Sylvia Plath.",
"Cumming deep inside my best bro.",
"Dad's funny balls.",
"Daddy's belt.",
"Death by Steven Seagal.",
"Deflowering the princess.",
"Demonic possession.",
"Dining with cardboard cutouts of the cast of Friends.",
"Disco fever.",
"Dorito breath.",
"Double penetration.",
"Drinking my bro's pee-pee right out of his peen.",
"Drinking ten 5-hour ENERGYs® to get fifty continuous hours of energy.",
"Dying alone and in pain.",
"Eating an albino.",
"Eating Tom Selleck’s mustache to gain his powers.",
"Emotional baggage.",
"Enormous Scandinavian women.",
"Existing.",
"Fabricating statistics.",
"Fetal alcohol syndrome.",
"Filling every orifice with butterscotch pudding.",
"Filling my son with spaghetti.",
"Finding Waldo.",
"Fisting.",
"Flying robots that kill people.",
"Four hours of truly goofy sex with the Blue Man Group.",
"Fuck Mountain.",
"Gandalf.",
"Gargling jizz.",
"Gay aliens.",
"Generational wealth.",
"Genetically engineered super-soldiers.",
"George Clooney's musk.",
"Getting abducted by Peter Pan.",
"Getting hilariously gang-banged by the Blue Man Group.",
"Getting your dick stuck in a Chinese finger trap with another dick.",
"Gladiatorial combat.",
"Going around punching people.",
"Grandpa's ashes.",
"Graphic violence, adult language, and some sexual content.",
"Having $57 in the bank.",
"Having a penis.",
"Having sex on top of a pizza.",
"Having shotguns for legs.",
"Hillary Clinton.",
"Ahiga.",
"Catfucker romet.",
"Eugene.",
"Hipsters.",
"Historical revisionism.",
"Hot brown piss.",
"Hot doooooooogs.",
"How awesome it is to be white.",
"How wet my pussy is.",
"Huge tits and a can-do attitude.",
"Indescribable loneliness.",
"Insatiable bloodlust.",
"Intimacy problems.",
"Jafar.",
"Jeff Goldblum.",
"Jesus.",
"Jumping out at people.",
"Just the tip.",
"Kim Jong-un.",
"Letting everyone down.",
"Leveling up.",
"Literally eating shit.",
"Living in a trash can.",
"Living in a trashcan.",
"Loki, the trickster god.",
"Mad hacky-sack skills.",
"Maintaining eye contact with a grown man while he takes a shit.",
"Making a friend.",
"Making shit up.",
"Making the penises kiss.",
"Masturbating in a robe like a rich person.",
"Maximal insertion.",
"Me.",
"Medieval Times® Dinner & Tournament.",
"Mild autism.",
"Mom.",
"Mooing.",
"Moral ambiguity.",
"Mufasa’s death scene.",
"Multiple orgasms.",
"My father, who died when I was seven.",
"My first kill.",
"My machete.",
"My manservant, Claude.",
"Neil Patrick Harris.",
"Not contributing to society in any meaningful way.",
"Not having sex."
]

promptte = [
"An international tribunal has found "                                                 ,
"And I would have gotten away with it, too, if it hadnt been for ",
"Awww, sick! I just saw this skater do a 720 kickflip into ",
"Dear Sir or Madam, We regret to inform you that the Office has denied your request for ",
"Doctor, youve gone too far! The human body wasnt meant to withstand that amount of ",
"Future historians will agree that the marking of the beginning of Americas decline will be ",
"He who controls the world controls ",
"I learned the hard way that you cant cheer up a grieving friend with ",
"In a pinch, it can be a suitable substitute for ",
"In his new self-produced album, Kanye West raps over the sounds of ",
"In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ",
"In Rome, there are whisperings that the Vatican has a secret room devoted to ",
"Michael Bays new three-hour action epic pits against ",
"My plan for world domination begins with ",
"Next season on Man vs, Wild, Bear Grylls must survive the depths of the Amazon with only  ",
"Next week on Discovery Channel, one man must survive in the depths of the Amazon with only  ",
"Science will never explain ",
"Science will never explain the origin of ",
"The CIA now interrogates enemy agents by repeatedly subjecting them to ",
"The secret to a lasting marriage is communication, communication, and ",
"The socialist governments of Scandinavia have declared that access to basic human right is ",
"What brought the orgy to a grinding halt? ",
"What has been making life difficult at the nudist colony? ",
"Whats the gift that keeps on giving? ",
"When all else fails, I can always masturbate to ",
"When I pooped, what came out of my butt? ",
"I would be woefully incomplete without ",
"StealthFl(a)shlight! Hours of fun. Easy to use. Perfect for ",
"A remarkable new study has shown that chimps have evolved their own primitive version of ",
"A successful job interview begins with a firm handshake and ends with ",
"After months of practice with , I think I’m finally ready for ",
"And I would have gotten away with it, too, if it hadnt been for ",
"And what did you bring for show and tell? ",
"As part of his contract, Prince won’t perform without ",
"As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ",
"Awww, sick! I just say this skater do a 720 kickflip into ",
"Before, all we had was ",
"Before I run for president, I must destroy all evidence of my involvement with ",
"Call the law offices of Goldstein & Goldstein, because no one should have to tolerate ",
"Charades was ruined for me forever when my mom had to act out ",
"Doctor, youve gone too far! The human body wasnt meant to withstand that amount of ",
"During high school I never really fit in until I found  ",
"During his midlife crisis, my dad got really into ",
"Finally! A service that delivers ",
"Having problems with ",
"Hey baby, come back to my place and I’ll show you ",
"I learned the hard way that you cant cheer up a grieving friend with ",
"I love being a mom. But its tough when my kids come home filthy from ",
"I spent my whole life working, only to have it ruined by ",
"I went from a fag to a nazi, all thanks to ",
"I’m not like the rest of you. I’m too rich and busy for ",
"If God didnt want us to enjoy porn, he wouldnt have given us ",
"In his newest and most difficult stunt, David Blaine must escape from ",
"In the seventh circle of Hell, sinners must endure ",
"Listen, son. If you want to get involved with this server, I won’t stop you. Just steer clear of ",
"Little Miss Muffet Sat on a tuffet, Eating her curds and ",
"Lovin’ you is easy ’cause you’re ",
"Members of New Yorks social elite are paying thousands of dollars just to experience ",
"Money can’t buy me love, but it can buy me ",
"My country, tis of thee, sweet land of ",
"My gym teacher got fired for adding ",
"My life is ruled by a vicious cycle of  ",
"My mom freaked out when she looked at my browser history and found ",
"My new favorite porn star is Joey ",
"My plan for world domination begins with ",
"Next time on Dr. Phil: How to talk to your child about ",
"Only two things in life are certain: death and ",
"Science will never explain ",
"The blind date was going horribly until we discovered our shared interest in ",
"The Five Stages of Grief: denial, anger, bargaining, acceptance and ",
"The healing process began when I joined a support group for victims of ",
"This is your captain speaking. Fasten your seatbelts and prepare for ",
"This months Cosmo: 'Spice up your sex life, in your bedroom get'",
"To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ",
"Tonight on 20/20: What you dont know could kill you - ",
"Welcome to this lovely server! Would you like to try our signature cocktail or ",
"What brought the orgy to a grinding halt? ",
"What has been making life difficult at the nudist colony? ",
"What left this stain on my couch? ",
"Whats harshing my mellow, man? ",
"When you get right down to it its just ",
"With enough time and pressure, this server will turn into ",
"You havent truly lived until youve experienced ",
"Your persistence is admirable, my dear Prince. But you cannot win my heart with "
]

responsenbc = [
" guilty of eating a whale dick",
" beached whale.",
": Hours of fun. Easy to use. Perfect for the children"
" big black dick.",
" bloody pacifier.",
" crappy little hand.",
" fat bald man from the internet.",
" Japanese tourist who wants something very badly but cannot communicate it.",
" low standard of living.",
" nuanced critique.",
" panty raid.",
" passionate Latino lover.",
" passionate tomboy lover.",
" plunger to the face.",
" rival dojo.",
" web of lies.",
" woman scorned.",
" atomic wedgie.",
" Etsy steampunk strap-on.",
" an evil man in evil clothes.",
" André the Giant's enormous, leathery scrotum.",
" Apologizing.",
" Appreciative snapping.",
" Ashton Kutcher.",
" Beating your wives.",
" Being a busy adult with many important things to do.",
" Being a dinosaur.",
" Big Bird's brown, crusty asshole.",
" Blaxploitation.",
" Bosnian chicken farmers.",
" Breaking nip slip news.",
" Carnies.",
" Clams.",
" Clenched butt cheeks.",
" Coughing into a vagina.",
" cutting.",
" dancing with a broom.",
" Dorito breath.",
" Eating an albino.",
" Fabricating statistics.",
" Finding a skeleton.",
" Genetically engineered super-soldiers.",
" George Clooney's musk.",
" Getting abducted by Peter Pan.",
" Getting in her pants, politely.",
" Gladiatorial combat.",
" Good grammar.",
" Having a penis.",
" Hipsters.",
" Historical revisionism.",
" Insatiable bloodlust.",
" Jafar.",
" Jean-Claude Van Damme in slow motion.",
" Jean-Claude Van Damme.",
" Just the tip.",
" Leveling up.",
" Literally eating shit.",
" Mad hacky-sack skills.",
" Making the penises kiss.",
" Media coverage.",
" Medieval Times® Dinner & Tournament.",
" Mom.",
" Moral ambiguity.",
" My machete.",
" Neil Patrick Harris.",
" NOOOOOOOOO!!!",
" Nubile slave boys.",
" Ominous background music.",
" One thousand Slim Jims.",
" Overpowering your father.",
" Panty raids.",
" Pistol-whipping a hostage.",
" Quiche.",
" Quivering jowls.",
" Revenge fucking.",
" Ripping into a man's chest and pulling out his still-beating heart.",
" Ryan Gosling riding in on a white horse.",
" Salvia.",
" Sanding off a man's nose.",
" Santa Claus.",
" Savagely beating a mascot.",
" Scrotum tickling.",
" Sexual humiliation.",
" Sexy Siamese twins.",
" Shaft.",
" Shitting out a screaming face.",
" Slow motion.",
" Space muffins.",
" Statistically validated stereotypes.",
" Stockholm Syndrome.",
" Sudden Poop Explosion Disease.",
" Suicidal thoughts.",
" Syphilitic insanity.",
" The boners of the elderly.",
" The economy.",
" The Femto® girls.",
" The four arms of Vishnu.",
" The four arms of Hitler-Shiva-Vishnu.",
" The Gulags.",
" The harsh light of day.",
" The hiccups.",
" The ooze.",
" The shambling corpse of Larry King.",
" The worst pain imaginable. Times two!",
" This guy!",
" Tripping balls.",
" Walking in on Dad peeing into Mom's mouth.",
" Words, words, words.",
" Zeus's sexual appetites.",
" 24-hour media coverage.",
" A 55-gallon drum of lube.",
" A big black dick.",
" A bigger, blacker dick.",
" A black-owned and operated business.",
" A bloody pacifier.",
" A boo-boo.",
" A botched circumcision.",
" A Burmese tiger pit.",
" A cat video so cute that your eyes roll back and your spine slides out of your anus.",
" A complicated relationship with food.",
" A cop who is also a dog.",
" A crappy little hand.",
" A dollop of sour cream.",
" A fat bald man from the internet.",
" A fortuitous turnip harvest.",
" A greased-up Matthew McConaughey.",
" A Japanese toaster you can fuck.",
" A Japanese tourist who wants something very badly but cannot communicate it.",
" A lamprey swimming up the toilet and latching onto your taint.",
" A low standard of living.",
" A magic hippie love cloud.",
" A man in yoga pants with a ponytail and feather earrings.",
" A nautical theme.",
" A nuanced critique.",
" A passionate Latino lover.",
" A phantasmagoria of anal delights.",
" A pile of squirming bodies.",
" A piñata full of scorpions.",
" A plunger to the face.",
" A PowerPoint presentation.",
" A sad fat dragon with no friends.",
" A sales team of clowns and pedophiles.",
" A slightly shittier parallel universe.",
" A smiling nigger, a latina businesswoman, a cool Asian, and some whites.",
" A sofa that says 'I have style, but I like to be comfortable.'",
" A spontaneous conga line.",
" A squadron of moles wearing aviator goggles.",
" A surprising amount of hair.",
" A sweaty, panting leather daddy.",
" A sweet spaceship.",
" A vagina that leads to another dimension.",
" A web of lies.",
" Actually getting shot, for real.",
" All my friends dying.",
" All of this blood.",
" An all-midget production of Shakespeare’s Richard III.",
" An army of skeletons.",
" An ass disaster.",
" An ether-soaked rag.",
" An Etsy steampunk strap-on.",
" An evil man in evil clothes.",
" An unhinged Ferris wheel rolling toward the sea.",
" An unstoppable wave of fire ants.",
" André the Giant's enormous, leathery scrotum.",
" Another shot of morphine.",
" Basic human decency.",
" Being a busy adult with many important things to do.",
" Being a dinosaur.",
" Being a hideous beast that no one could love.",
" Being awesome at sex.",
" Being a nigger.",
" Being fat from noodles.",
" Being white.",
" Big bad mama nipples.",
" Big Bird's brown, crusty asshole.",
" Big ol' floppy titties.",
" Bill Clinton, naked on a bearskin rug with a saxophone.",
" Blood farts.",
" Blowing some dudes in an alley.",
" Boris the Soviet Love Hammer.",
" Bosnian chicken farmers.",
" Bullshit.",
" Buying the right pants to be cool.",
" Catastrophic urethral trauma.",
" Chugging a lava lamp.",
" Clams.",
" Clenched butt cheeks.",
" Cock.",
" Consent.",
" Converting to Islam.",
" Crabapples all over the fucking sidewalk.",
" Crushing Mr. Peanut's brittle body.",
" Crying into the pages of Sylvia Plath.",
" Cumming deep inside my best bro.",
" Dad's funny balls.",
" Daddy's belt.",
" Death by Steven Seagal.",
" Deflowering the princess.",
" Demonic possession.",
" Dining with cardboard cutouts of the cast of Friends.",
" Disco fever.",
" Dorito breath.",
" Double penetration.",
" Drinking my bro's pee-pee right out of his peen.",
" Drinking ten 5-hour ENERGYs® to get fifty continuous hours of energy.",
" Dying alone and in pain.",
" Eating an albino.",
" Eating Tom Selleck’s mustache to gain his powers.",
" Emotional baggage.",
" Enormous Scandinavian women.",
" Existing.",
" Fabricating statistics.",
" Fetal alcohol syndrome.",
" Filling every orifice with butterscotch pudding.",
" Filling my son with spaghetti.",
" Finding Waldo.",
" Fisting.",
" Flying robots that kill people.",
" Four hours of truly goofy sex with the Blue Man Group.",
" Fuck Mountain.",
" Gandalf.",
" Gargling jizz.",
" Gay aliens.",
" Generational wealth.",
" Genetically engineered super-soldiers.",
" George Clooney's musk.",
" Getting abducted by Peter Pan.",
" Getting hilariously gang-banged by the Blue Man Group.",
" Getting your dick stuck in a Chinese finger trap with another dick.",
" Gladiatorial combat.",
" Going around punching people.",
" Grandpa's ashes.",
" Graphic violence, adult language, and some sexual content.",
" Having $57 in the bank.",
" Having a penis.",
" Having sex on top of a pizza.",
" Having shotguns for legs.",
" Hillary Clinton.",
" Ahiga.",
" Catfucker romet.",
" Eugene.",
" Hipsters.",
" Historical revisionism.",
" Hot brown piss.",
" Hot doooooooogs.",
" How awesome it is to be white.",
" How wet my pussy is.",
" Huge tits and a can-do attitude.",
" Indescribable loneliness.",
" Insatiable bloodlust.",
" Intimacy problems.",
" Jafar.",
" Jeff Goldblum.",
" Jesus.",
" Jumping out at people.",
" Just the tip.",
" Kim Jong-un.",
" Letting everyone down.",
" Leveling up.",
" Literally eating shit.",
" Living in a trash can.",
" Living in a trashcan.",
" Loki, the trickster god.",
" Mad hacky-sack skills.",
" Maintaining eye contact with a grown man while he takes a shit.",
" Making a friend.",
" Making shit up.",
" Making the penises kiss.",
" Masturbating in a robe like a rich person.",
" Maximal insertion.",
" Me.",
" Medieval Times® Dinner & Tournament.",
" Mild autism.",
" Mom.",
" Mooing.",
" Moral ambiguity.",
" Mufasa’s death scene.",
" Multiple orgasms.",
" My father, who died when I was seven.",
" My first kill.",
" My machete.",
" My manservant, Claude.",
" Neil Patrick Harris.",
" Not contributing to society in any meaningful way.",
" Not having sex."
]